---
name: docker-broker

instance_groups:
- name: subway
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: subway-broker
    release: cf-subway
    consumes:
      backend:
        from: backend
    provides:
      subway:
        as: broker
        shared: true
    properties:
      username: broker
      password: ((subway-broker-password))
      name: docker-broker

- name: docker
  azs: [z1,z2,z3]
  instances: 3
  persistent_disk: 65536
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: docker
    release: docker
    properties:
      tcp_address: 0.0.0.0
      tls_cacert: "((docker-tls.ca))"
      tls_cert: "((docker-tls.certificate))"
      tls_key: "((docker-tls.private_key))"

  - name: cf-containers-broker
    release: docker
    provides:
      cf-containers-broker:
        as: backend
        shared: true
    properties:
      username: broker
      password: ((docker-broker-password))
      cookie_secret: ((docker-broker-cookie-secret))
      max_containers: 20
      fetch_images: true
      services: []

- name: sanity-test
  azs: [z1]
  lifecycle: errand
  instances: 1
  persistent_disk: 65536
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: sanity-test-broker
    release: docker
    consumes:
      servicebroker:
        from: broker
      docker-broker-catalog:
        from: backend
  - name: docker
    release: docker
    properties:
      tcp_address: 0.0.0.0
      tls_cacert: "((docker-tls.ca))"
      tls_cert: "((docker-tls.certificate))"
      tls_key: "((docker-tls.private_key))"

variables:
- name: subway-broker-password
  type: password
- name: docker-broker-password
  type: password
- name: docker-broker-cookie-secret
  type: password
- name: docker-ca
  type: certificate
  options:
    is_ca: true
    common_name: dockerCA
- name: docker-tls
  type: certificate
  options:
    ca: docker-ca
    common_name: docker
    extended_key_usage:
    - client_auth

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 0
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 32
  serial: false

releases:
- name: cf-subway
  version: 3.2.0
  url: https://bosh.io/d/github.com/cloudfoundry-community/cf-subway-boshrelease?v=3.2.0
  sha1: 57de13d5a7b4709c065b6f909cd86372badfe2da
- name: docker
  version: 30.1.0
  url: https://github.com/cloudfoundry-community/docker-boshrelease/releases/download/v30.1.0/docker-30.1.0.tgz
  sha1: bcc2e859836415c37b5a668eff5d17761e5321b5
